### ISSUE TITLE
Fail with Nuxt 3 RC 9

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-community/device-module#122]
Hello,

When upgrading to version Nuxt 3 RC 9 the component fails

**Comment by agracia-foticos** [comment]
WARN  Module device-module is disabled due to incompatibility issues:                                                                          13:15:46
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.9`

**Comment by Redemption198** [comment]
> I have updated to RC 13 version and it is throwing me an error.
> 
> Nuxi 3.0.0-rc.13 Nuxt 3.0.0-rc.13 with Nitro 0.6.1
> 
> > Local:    http://localhost:3000/
> > Network:  http://172.17.0.2:3000/
> 
> information_source Using default Tailwind CSS file from runtime/tailwind.css
> 
> ERROR Cannot start nuxt: Cannot find module '/var/www/project/node_modules/@nuxtjs/device/dist/module.cjs'
> 
> at createEsmNotFoundErr (node:internal/modules/cjs/loader:1012:15) at finalizeEsmResolution (node:internal/modules/cjs/loader:1005:15) at resolveExports (node:internal/modules/cjs/loader:522:14) at Function.Module._findPath (node:internal/modules/cjs/loader:562:31) at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27) at Function.resolve (node:internal/modules/cjs/helpers:109:19) at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:243302) at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:240:29) at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:445:18) at installModule (node_modules/@nuxt/kit/dist/index.mjs:426:47)
> 
> ![image](https://user-images.githubusercontent.com/77386602/200522752-bcad8177-f9f1-4537-9021-8c796042730c.png)

I removed the `dist` folder from the repository and I'm waiting for someone to review and merge the [PR](https://github.com/nuxt-community/device-module/pull/119), in the meanwhile you can install the module from an older commit that has the `dist` folder by doing `yarn add Redemption198/device-module#2136ea0` or `npm install Redemption198/device-module#2136ea0`

**Comment by agracia-foticos** [comment]
solved!
