### ISSUE TITLE
Nuxt v2 does not see the @nuxtjs/device module

### ISSUE THREAD

**Issue by siarheiSiniauski** [nuxt-community/device-module#126]
` 
"dependencies": {
    "nuxt": "^2.15.8",
  },
  "devDependencies": {
    "@nuxtjs/device": "^3.0.0"
  }
`

`console.log('$device', this.$device)`

![image](https://user-images.githubusercontent.com/14168392/202725410-fea12070-acc0-4486-ba9b-eb53c67d7405.png)

![image](https://user-images.githubusercontent.com/14168392/202725029-19fbcfa6-a690-4a6a-a411-401be95e24f4.png)

**Comment by siarheiSiniauski** [comment]
I found the solution myself, you need to put a lower version

`yarn add @nuxtjs/device@^2.1.0 -D`

**Comment by dotneet** [comment]
Thank you for reporting.
I've updated README.
