### ISSUE TITLE
Offer to move to nuxt-community

### ISSUE THREAD

**Issue by pi0** [nuxt-community/device-module#13]
Hi! This is a really nice module. If you wish we can move it to a more official namespace (`nuxt-community/device-module` and `@nuxtjs/device`).

If you wish, here are steps:
- [x] We will send you invitations for GitHub and NPM
- [x] Move the repository to nuxt-community
- [ ] A PR to make repo compatible with [module-template](https://github.com/nuxt-community/module-template)
- [ ] Publish under `@nuxtjs` and offer users using the new package. deprecating current one.

**Comment by dotneet** [comment]
Hi, @pi0 

Yes, I wish that!

**Comment by pi0** [comment]
Great! I've sent you invitations to move repository.

**Comment by dotneet** [comment]
@pi0 
Thanks! I've accepted the invitations.

Should I rename this repo to `device-module` before transfer this repo to nuxt-comminity?

**Comment by pi0** [comment]
@dotneet yes please :)

**Comment by dotneet** [comment]
@pi0 
I've finished publishing npm package to nuxtjs namespace.
Latest version is 1.2.2 for my mistake. (1.2.0 and 1.2.1 are not published.)

https://www.npmjs.com/package/@nuxtjs/device

**Comment by pi0** [comment]
Great for publish! So i think the only remaining thing is using `npm deprecate` to deprecate old package and offer users migrating.

**Comment by dotneet** [comment]
Done.
https://www.npmjs.com/package/nuxt-device-detect/access

**Comment by pi0** [comment]
Great! Welcome to nuxt community mate ;)

**Comment by dotneet** [comment]
Thank you!
