### ISSUE TITLE
No TypeScript definition file?

### ISSUE THREAD

**Issue by MasterHiei** [nuxt-community/device-module#17]
Hi, I couldn't find `types.d.ts` file in `node_modules` after moved to this module. How to import it?

**Comment by dotneet** [comment]
Hi, @MasterHiei 
Thank you for reporting.
I've fixed it and publish new version to npm.
Please check it.

**Comment by MasterHiei** [comment]
Thank you! @dotneet 
I have updated to the new version and fixed it.
