### ISSUE TITLE
Not working when generating static pages

### ISSUE THREAD

**Issue by phr3nzy** [nuxt-community/device-module#21]
Much appreciated for the work in this module.

Although it works on SPA & SSR, it doesn't work when you statically generate pages. Any fix for this? Thanks

**Comment by dotneet** [comment]
Hi, @paulgv 

Expressions in a template are evaluated on running generate command so detecting a user agent is not possible.
You can use defaultUserAgent option to specify user-agent on the time.

https://github.com/nuxt-community/device-module#options

**Comment by mattkaye** [comment]
This didn't work for me. Logging from`this.$device.isMobile` from `npm run generate` still returns false. I ended up using `window.matchMedia` in a `process.client` conditional block to solve my specific task.
