### ISSUE TITLE
Can you add a name of device?

### ISSUE THREAD

**Issue by StanZhuravlev** [nuxt-community/device-module#24]
Hi!

For various purposes, I would like to be able to know the name of the type of device. For example, to be able to specify <div :class="$device.type">, where type - can assign with strings 'mobile', 'tablet', 'desktop'. 

Now I use my own plugin, which on the basis of the device-module library generates need values. 

Is it possible to ask to add in next version of Your library native support for this feature?

**Comment by dotneet** [comment]
PR is always welcome!

**Comment by Atinux** [comment]
Will follow conversation on #55
