### ISSUE TITLE
Different behavior on production with errors

### ISSUE THREAD

**Issue by eslamoo** [nuxt-community/device-module#27]
Firstly i would like to thank you for your great effort on this project.
I have two layouts one for desktop and one for mobile so i built my components exactly same as your documentation and here is the code:

           <div v-if="$device.isDesktop">
			Desktop

		</div>

		<div v-if="$device.isMobile">

			Mobile

		</div>`
`
		 export default {
	layout: (ctx) => ctx.isMobile ? 'mobile' : 'main'
}`
its work fine on dev mode but when i run `npm run generate` or `npm run build` everything changes the mobile layout won't be apply on mobile.
in addition this error appears on console  
![Screenshot_1](https://user-images.githubusercontent.com/32875906/69750194-d9f72800-1154-11ea-8f9d-12a7cf957c53.png)
 NOTE: when i add this line ` { defaultUserAgent: 'Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Mobile Safari/537.36' }` The opposite happens, mobile layout applied on desktop and mobile.

I see this problem constantly repeating, so please provide a solution as soon as possible.
Thanks in advance

**Comment by dotneet** [comment]
1. error message
I can't reproduce the error displayed on console.
Please create a minimum repository that reproduce the error.

2. about generate command
A device type is resolved on the time of running generate command.
https://github.com/nuxt-community/device-module/issues/21

**Comment by eslamoo** [comment]
@dotneet Thanks for your response:

  1. Here is the [repo](https://github.com/eslamoo/device-issue) you asked for, you can serve the `/dist` folder and see the error in the console.
  2. after checking this issue #21 i cant get what you mean, and i cant realize how its work, So I think that would be better to provide us with a working example, or apply it on my repo. Thank you :)

**Comment by dotneet** [comment]
@eslamoo 

1. I can't reproduce the error with that repo...  tell me the details of your environment(node version, os)

2. We can't detect a device type dynamically when open a page generated by generate command. It's the specification of generate command.

**Comment by eslamoo** [comment]
@dotneet 

     1.node: v10.17.0 / os : Ubuntu 18.04.3 LTS
     2. If this module can not detect the type of device in the production so what does it offer? All I want is to differentiate between desktop and mobile in the production if there is a working example to it please provide it because my project blocked because of this point.

**Comment by dotneet** [comment]
This module can detect the type of device with spa and ssr mode even if production mode.
Your [repo](https://github.com/eslamoo/device-issue) works correctly in my environment.
But can't detect the type only when use generate command. this is the specification of nuxt.

**Comment by eslamoo** [comment]
Please can you tell me how to make it work on production mode? just to can switch between desktop and mobile layout, cuz i cant get this from here #21

**Comment by dotneet** [comment]
@eslamoo 

In your repo 

```bash
npm run build
npm start
```
open http://localhost:3000/ with chrome then switch user-agent using chrome developer tool and reload.

**Comment by eslamoo** [comment]
Thanks i was running command `serve dist` but it should be `npm start`
