### ISSUE TITLE
how to use inside a store

### ISSUE THREAD

**Issue by xerosanyam** [nuxt-community/device-module#40]
Hi, thanks for the great effort. I wanted to know if there's some simple way to access this inside store? 1 step further, inside any plain js file?

**Comment by dotneet** [comment]
Hi, @xerosanyam.

You can use `this.$device` like the answer below.
https://stackoverflow.com/a/57771094/4221452

**Comment by xerosanyam** [comment]
Thanks!

**Comment by xerosanyam** [comment]
For future reference: `nuxtServerInit` is important to use in store.
