### ISSUE TITLE
How to get device with Nuxt Generate

### ISSUE THREAD

**Issue by tavsanrabit** [nuxt-community/device-module#46]
Doesnt work on first open with nuxt-generate. can this not be done. or is there a way around this.

**Comment by axelerod12** [comment]
I'm having this issue as well. Any solution for this?

**Comment by dotneet** [comment]
Did you check defaultUserAgent option?
https://github.com/nuxt-community/device-module#options

It's not possible to detect a device at opening a page that is generated by `nuxt generate` from its mechanism.

**Comment by fabiofdsantos** [comment]
Why not using [window.matchMedia](https://developer.mozilla.org/pt-BR/docs/Web/API/Window/matchMedia)?
