### ISSUE TITLE
module not registered in NPM

### ISSUE THREAD

**Issue by ronen-e** [nuxt-community/device-module#49]
Hi I'm getting an npm error:

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nuxtjs%2fdevice - Not found
npm ERR! 404 
npm ERR! 404  '@nuxtjs/device@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by dotneet** [comment]
@ronen-e 
NPM is down at now.
https://status.npmjs.org/
