### ISSUE TITLE
keep-alive doesn't work with @nuxt/device

### ISSUE THREAD

**Issue by DanLowo** [nuxt-community/device-module#51]
Everything has been going well using module, but i noticed that the browser no longer caches my pages again (using fetch & keep-alive) when i use this module for dynamic layouts (like shown in the docs : 
 **layout: (ctx) => ctx.isMobile ? "mobile" : "desktop"**).

**Comment by Atinux** [comment]
This is intended behaviour @DanLowo, since the component is kept-alive, it won't call the `layout` property anymore.
