### ISSUE TITLE
Flagging Facebook/Instagram in-app browser as mobile

### ISSUE THREAD

**Issue by JasonGotGithub** [nuxt-community/device-module#58]
This is just an idea, but it would nice to have the Facebook and Instagram in-app browsers flagged as isMobile. Currently, I just add a check myself for FBAN, FBAV and Instagram in the UA.

**Comment by JasonGotGithub** [comment]
I haven't had any issues with Twitter regarding the isMobile flag

**Comment by JasonGotGithub** [comment]
On it 🙌

**Comment by dotneet** [comment]
@JasonGotGithub Thanks! Your [PR](https://github.com/nuxt-community/device-module/pull/59) has been merged.
