### ISSUE TITLE
It is not works if I change device in developer panel 

### ISSUE THREAD

**Issue by xreider** [nuxt-community/device-module#60]
I've made window resize listener, it works. But...
I open website as a PC, change to mobile view in developer panel, an the $device is still showing that is desctop

**Comment by xreider** [comment]
> Try to refresh the page then

I need know device dynamically

**Comment by eleave** [comment]
> Try to refresh the page then

Hey, guys. First wanna thank you for this nice module.
I have similar problems here and refresh did not solve the situation.
What I do:

1. Start dev as usually: `npm run dev`.
2. In my layouts/clear.vue file I use $device in template to set a class attribute.
3. Turn on the device toolbar in Opera Devtools too see a mobile device simulation.  
4. And it's "isDesktop" class... ok, I refresh the page then, but still desktop here.

But in **mounted()** method console.log shows me `this.$device.isMobileOrTablet` is true. And if I change anything in my component to make Nuxt an reactive update in browser then I see "isMobile" in template too.

![image](https://user-images.githubusercontent.com/34356472/109146012-b4543680-777c-11eb-84ce-220a6186e7ea.png)

Also I tried set this class with a computed property (did not work). Could you tell me what am I doing wrong?

**Comment by fdemir** [comment]
Any updates? I think this module has to handle window resize. I'm sure that so many users having this problem. It's not reactive.

**Comment by dotneet** [comment]
@xreider  @eleave  @fdemir 
I've experimentally implemented #65.
Is it suitable for your case?
Please test it if you have time.

**Comment by eleave** [comment]
> I've experimentally implemented #65.
> Is it suitable for your case?
> Please test it if you have time.

Yes, with refresh button it does work as expected, I have tested it with toggle device toolbar, ty!

**Comment by dotneet** [comment]
v2.1.0 has been released with refreshOnResize option.
