### ISSUE TITLE
detecting crawlers

### ISSUE THREAD

**Issue by M-Barari** [nuxt-community/device-module#70]
is there any flag to detects bots and crawlers? I'm currently use [nuxt-user-agent](https://github.com/fukuiretu/nuxt-user-agent) to check for crawlers and appreciate to have crawler detector on this package so I can only use one package.

**Comment by dotneet** [comment]
@M-Barari 
I'll try to implment that(isCrawler flag) at #68

**Comment by dotneet** [comment]
@M-Barari 
v2.1.0 has been released with support for isCrawler flag.
